_default:
    just --list --unsorted

# Client commands
#################

run:
    yarn
    yarn vite --open

preview:
    yarn
    yarn vite preview

build:
    yarn
    yarn tsc
    yarn vite build

run-build:
    yarn vite preview --open
