_default:
    just --list --unsorted

# Commands
##########

run: _deps
    yarn vite --open --clearScreen=false

build-run: build run-build

build: _deps
    yarn tsc
    yarn vite build

run-build: _deps
    yarn vite preview --open --clearScreen=false

# Hidden
########

_deps:
    yarn