# Commands
##########

run: _deps
    bun install
    bun run --hot src/server.ts

build: _deps
    @echo "Build from root of the project instead"


# Hidden
########

_deps:
    @ just _install_if_not_exists bun "brew tap oven-sh/bun && brew install bun"

_install_if_not_exists name install_cmd:
    #!/bin/zsh
    if ! which "{{name}}" > /dev/null; then
        echo "install {{name}}"
        echo "Running: '{{install_cmd}}'"
        {{install_cmd}}
    fi
